/*
** Copyright © Bart Kampers
*/


package bka.graph.swing;


import bka.graph.Vertex;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.tree.*;


class VertexTreePanel extends javax.swing.JPanel {


    VertexTreePanel(GraphEditor graphEditor) {
        this.graphEditor = graphEditor;
        initComponents();
        tree.setCellRenderer(new CellRenderer());
        tree.addMouseListener(MOUSE_ADAPTER);
        tree.addKeyListener(KEY_ADAPTER);
    }
    
    
    void rebuild() {
        rootNode.removeAllChildren();
        for (DiagramComponent diagramComponent : graphEditor.getDiagramComponents()) {
            DiagramNode diagramNode = new DiagramNode(diagramComponent);
            rootNode.add(diagramNode);
            for (VertexPicture vertexPicture : diagramComponent.getVertexPictures()) {
                VertexPictureNode vertexPictureNode = new VertexPictureNode(vertexPicture, diagramComponent);
                diagramNode.add(vertexPictureNode);
            }
        }
        treeModel.nodeStructureChanged(rootNode);
        Enumeration en = rootNode.children();
        while (en.hasMoreElements()) {
            DiagramNode diagramNode = (DiagramNode) en.nextElement();
            expand(diagramNode);
        }
    }
    
    
    void diagramEntered(MouseEvent evt) {
        if (dragInfo != null) {
            dragInfo.diagramComponent = (DiagramComponent) evt.getComponent();
            boolean cannotDrop = dragInfo.diagramComponent.contains(dragInfo.picture);
            Image image = (cannotDrop) ? dragInfo.createCannotDropImage() : dragInfo.createImage();
            dragInfo.diagramComponent.setCursor(createCursor(image, "DropVertexCursor"));
        }
    }
    
    
    void diagramExited() {
        if (dragInfo != null) {
            if (dragInfo.diagramComponent != null) {
                dragInfo.diagramComponent.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
            dragInfo.diagramComponent = null;
        }
    }
    
    
    void diagramModified(DiagramComponent diagramComponent) {
        DiagramNode diagramNode = findDiagramNode(diagramComponent);
        if (diagramNode != null) {
            treeModel.nodeChanged(diagramNode);
        }
    }
    
    
    void vertexAdded(VertexPicture vertexPicture, DiagramComponent diagramComponent) {
        DefaultMutableTreeNode parentNode = findNode(diagramComponent);
        VertexPictureNode vertexNode = new VertexPictureNode(vertexPicture, diagramComponent);
        parentNode.add(vertexNode);
        treeModel.nodeStructureChanged(parentNode);
        expand(parentNode);
    }
    
    
    void vertexModified(VertexPicture vertexPicture) {
        DefaultMutableTreeNode vertexNode = findNode(vertexPicture);
        if (vertexNode != null) {
            treeModel.nodeChanged(vertexNode);
        }
    }
    
    
    void vertexRemoved(VertexPicture vertexPicture) {
        DefaultMutableTreeNode vertexPictureNode = findNode(vertexPicture);
        if (vertexPictureNode != null) {
            TreeNode parent = vertexPictureNode.getParent();
            vertexPictureNode.removeFromParent();
            treeModel.nodeStructureChanged(parent);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();

        setMinimumSize(new java.awt.Dimension(200, 300));

        tree.setModel(treeModel);
        tree.setRootVisible(false);
        scrollPane.setViewportView(tree);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(scrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(scrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private DiagramNode findDiagramNode(DiagramComponent diagramComponent) {
        Enumeration en = rootNode.children();
        while (en.hasMoreElements()) {
            DiagramNode node = (DiagramNode) en.nextElement();
            if (node.getUserObject() == diagramComponent) {
                return node;
            }
        }
        return null;
    }

    
    private DefaultMutableTreeNode findNode(Object userObject) {
        return findNode(userObject, rootNode);
    }
    
    
    private DefaultMutableTreeNode findNode(Object userObject, DefaultMutableTreeNode parent) {
        Enumeration en = parent.children();
        while (en.hasMoreElements()) {
            DefaultMutableTreeNode child = (DefaultMutableTreeNode) en.nextElement();
            if (child.getUserObject() == userObject) {
                return child;
            }
            else {
                DefaultMutableTreeNode node = findNode(userObject, child);
                if (node != null) {
                    return node;
                }
            }
        }
        return null;
    }

    
    private void expand(DefaultMutableTreeNode node) {
        TreeNode[] pathNodes = node.getPath();
        TreePath treePath = new TreePath(pathNodes);
        tree.expandPath(treePath);
    }


    private static Cursor createCursor(Image image, String name) {
        int width = image.getWidth(null);
        int height = image.getHeight(null);
        Point center = new Point(width / 2, height / 2);
        return Toolkit.getDefaultToolkit().createCustomCursor(image, center, name);
    }

    
    private class DiagramNode extends DefaultMutableTreeNode {
    
        DiagramNode(DiagramComponent diagramComponent) {
            super(diagramComponent);
        }
        
        @Override
        public String toString() {
            return ((DiagramComponent) getUserObject()).getTitle();
        }
    
    }
    
    
    private class VertexPictureNode extends DefaultMutableTreeNode {
        
        VertexPictureNode(VertexPicture vertexPicture, DiagramComponent diagramComponent) {
            super(vertexPicture);
            this.diagramComponent = diagramComponent;
        }
        
        @Override
        public String toString() {
            VertexPicture vertexPicture = ((VertexPicture) getUserObject());
            Vertex vertex = vertexPicture.getVertex();
            assert vertex != null;
            String name = vertex.getName();
            if (name == null) {
                name = vertex.getClass().getSimpleName();
            }
            VertexPicture container = diagramComponent.findContainer((VertexPicture) getUserObject());
            if (container != null) {
                assert container.getVertex() != null;
                String containerName = container.getVertex().getName();
                if (containerName != null) {
                    name += " @ " + container.getVertex().getName();
                }
            }
            return (name != null) ? name : vertex.getClass().getSimpleName();
        }
        
        DiagramComponent diagramComponent;
        javax.swing.Icon icon;

    }
    
    
    static class CellRenderer extends DefaultTreeCellRenderer {

        @Override
        public Component getTreeCellRendererComponent(javax.swing.JTree tree, java.lang.Object value, boolean selected, boolean expanded, boolean leaf, int row, boolean hasFocus) {
            super.getTreeCellRendererComponent(tree, value, selected, expanded, leaf, row, hasFocus);
            createIcon(value);
            return this;
        }
        
        private void createIcon(java.lang.Object value) {
            java.lang.Class nodeClass = value.getClass();
            if (value instanceof VertexPictureNode) {
                nodeClass = ((VertexPictureNode) value).getUserObject().getClass();
            }
            synchronized (ICONS) {
                javax.swing.Icon icon = null;
                if (ICONS.containsKey(nodeClass)) {
                    icon = ICONS.get(nodeClass);
                }
                else {
                    if (value instanceof VertexPictureNode) {
                        icon = ((VertexPicture) ((VertexPictureNode) value).getUserObject()).createIcon(16, 14);
                        ICONS.put(nodeClass, icon);
                    }
                }
                if (icon != null) {
                    setIcon(icon);
                }
            }
        } 
    }
    
    
    private DefaultMutableTreeNode getSelectedNode() {
        TreePath path = tree.getSelectionPath();
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) path.getLastPathComponent();
        return node;
    }


    private class DragInfo {
        
        VertexPicture picture;
        DiagramComponent diagramComponent;

        Image createImage() {
            return picture.createImage(16, 14);
        }

        Image createCannotDropImage() {
            Image image = createImage();
            Graphics graphics = image.getGraphics();
            int width = image.getWidth(null);
            int height = image.getHeight(null);
            graphics.setColor(Color.red);
            graphics.drawLine(0, 0, width, height);
            return image;
        }


    }
    
    
    private final MouseAdapter MOUSE_ADAPTER = new MouseAdapter() {
        
        @Override
        public void mousePressed(MouseEvent evt) {
            if (evt.getClickCount() == 1) {
                DefaultMutableTreeNode node = getSelectedNode();
                if (node instanceof VertexPictureNode) {
                    startPictureDrag(node);
                }
            }
        }

        @Override
        public void mouseReleased(MouseEvent evt) {
            if (evt.getClickCount() == 1) {
                finishDrag(evt.getLocationOnScreen());
            }
        }

        @Override
        public void mouseClicked(MouseEvent evt) {
            if (evt.getClickCount() == 2) {
                selectPictureInDiagram(getSelectedNode());
            }
        }

        private void startPictureDrag(DefaultMutableTreeNode node) {
            dragInfo = new DragInfo();
            dragInfo.picture = (VertexPicture) node.getUserObject();
            Image image = dragInfo.createImage();
            setCursor(createCursor(image, "DragVertexCursor"));
        }
       
        private void finishDrag(Point locationOnScreen) {
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            if (dragInfo != null && dragInfo.diagramComponent != null) {
                dragInfo.diagramComponent.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                DefaultMutableTreeNode selectedNode = getSelectedNode();
                if (selectedNode instanceof VertexPictureNode) {
                    VertexPicture selectedPicture = (VertexPicture) selectedNode.getUserObject();
                    dragInfo.diagramComponent.addVertexPictureCopy(selectedPicture, locationOnScreen);
                }
            }
            dragInfo = null;
        }

        private void selectPictureInDiagram(DefaultMutableTreeNode node) {
            DefaultMutableTreeNode parent = (DefaultMutableTreeNode) node.getParent();
            DiagramComponent diagramComponent = (DiagramComponent) parent.getUserObject();
            diagramComponent.setSelected((AbstractPicture) node.getUserObject());
            graphEditor.setSelected((DiagramComponent) parent.getUserObject());
        }

    };


    private final KeyAdapter KEY_ADAPTER = new KeyAdapter() {

        @Override
        public void keyReleased(KeyEvent evt) {
            if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
                DefaultMutableTreeNode node = getSelectedNode();
                if (node.getUserObject() instanceof VertexPicture) {
                    DefaultMutableTreeNode parent = (DefaultMutableTreeNode) node.getParent();
                    DiagramComponent diagramComponent = (DiagramComponent) parent.getUserObject();
                    diagramComponent.removeVertex((VertexPicture) node.getUserObject());
                }
            }
        }
    };


    private final GraphEditor graphEditor;
    
    
    private DragInfo dragInfo;
    

    private final DefaultMutableTreeNode rootNode = new DefaultMutableTreeNode();
    private final DefaultTreeModel treeModel = new DefaultTreeModel(rootNode);
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables

    private static final Map<java.lang.Class, javax.swing.Icon> ICONS = new HashMap<>();
    
}
